# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in testcontainers-compose.gemspec
gemspec

# Use the latest version of testcontainers-core from the local path
gem "testcontainers-core", path: "../core"
